workflows:
  cashew-workflow:
    name: Cashew Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        # Cambia estos valores si quieres firmar la app para Google Play
        ANDROID_KEYSTORE: ""  # deja vacío si no firmas
        ANDROID_KEYSTORE_PASSWORD: ""
        ANDROID_KEY_ALIAS: ""
        ANDROID_KEY_PASSWORD: ""
    scripts:
      - name: Get dependencies
        script: |
          cd budget
          flutter pub get
      - name: Build APK
        script: |
          cd budget
          flutter build apk --release
      # Para app bundle (.aab) en vez de APK, descomenta la siguiente línea
      # - name: Build App Bundle
      #   script: |
      #     cd budget
      #     flutter build appbundle --release
    artifacts:
      - budget/build/app/outputs/flutter-apk/*.apk
      # Para .aab, cambia la línea a
